In [2]:
import numpy as np

In [4]:
mylist = [1,2,3]


In [5]:
type(mylist)

list

In [6]:
 myarray = np.array(mylist)

In [7]:
myarray

array([1, 2, 3])

In [8]:
type(myarray)

numpy.ndarray

In [ ]:
np.arange(0, 10, 2)

In [4]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(shape=(5,6)) 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [20]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [21]:
arr2 = np.random.randint(0, 100, 10)

In [22]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [23]:
arr.max()

95

In [24]:
arr.argmax()

0

In [25]:
arr.argmin()

7

In [26]:
arr.mean()

60.8

In [27]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])